name: build-gh-pages

on: workflow_dispatch

jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    env:
      USE_CIM_VERSION_2_4_15: CGMES_2.4.15_27JAN2020
      USE_CIM_VERSION_3_0_0: CGMES_3.0.0
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Doxygen
      run: sudo apt-get install doxygen
      shell: bash
    - name: Install Graphviz
      run: sudo apt-get install graphviz
      shell: bash

    - name: USE_CIM_VERSION_2_4_15 Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_2_4_15}}
    - name: USE_CIM_VERSION_2_4_15 Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_2_4_15}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_2_4_15}}
          cmake ../.. -DUSE_CIM_VERSION=${{env.USE_CIM_VERSION_2_4_15}}
          make doc
    - name: USE_CIM_VERSION_2_4_15 Copy
      run: |
          mkdir -p ./copy_files/docs
          cp -r ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_2_4_15}}/doc/html ./copy_files/docs/${{env.USE_CIM_VERSION_2_4_15}}

    - name: USE_CIM_VERSION_3_0_0 Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_3_0_0}}
    - name: USE_CIM_VERSION_3_0_0 Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_3_0_0}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_3_0_0}}
          cmake ../.. -DUSE_CIM_VERSION=${{env.USE_CIM_VERSION_3_0_0}}
          make doc
    - name: USE_CIM_VERSION_3_0_0 Copy
      run: |
          mkdir -p ./copy_files/docs
          cp -r ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION_3_0_0}}/doc/html ./copy_files/docs/${{env.USE_CIM_VERSION_3_0_0}}
          cp ./README.md ./copy_files/docs/README.md

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./copy_files
        force_orphan: true
        keep_files: false
        publish_branch: gh-pages
