name: Package build workflow

on:
  push:
    tags:
      - 'release/v*'

jobs:
  package:
    runs-on: ubuntu-latest
    name: A job to build the packages
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      id:   build-it-now
      uses: ./package/
    - name: UploadRPM
      uses: actions/upload-artifact@v3
      with:
        name: rpm
        path: ${{ github.workspace }}/build/*.rpm
    - name: UploadDEB
      uses: actions/upload-artifact@v3
      with:
        name: deb
        path: ${{ github.workspace }}/build/*.deb
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
    - name: GetArtifact
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rpm/*
          deb/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
